# Mandatory settings

name: Arvind Ravi
paginate: 25
url: http://arvindravi.com # add your site url (format: https://example.com/)
blog_theme: light # Or use dark

# Optional settings

about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: arvindravi # Add your Disqus identifier
ga_analytics: UA-37200107-6 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: false # Change to false if not
scrollappear_enabled: true # Change to false to disable
social:
  dribbble: arvindravi # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: arvindravi_ # Add your Twitter handle
  email: hello@arvindravi.com # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
    - _assets/stylesheets/modules
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
